# Generated by Django 4.0.4 on 2022-05-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_No', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('resume_url', models.CharField(max_length=100)),
                ('experience', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('age', models.IntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.gender')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
