# Generated by Django 4.0.4 on 2022-05-07 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
