# Generated by Django 4.0.4 on 2022-05-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='candidates.status'),
        ),
    ]
